version: '3'
services:
  config-server:
    image: tiger123/config-server:master
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - sab-network-dev
  registry:
    image: tiger123/sab-service-registry:master
    container_name: registry
    ports:
      - "8761:8761"
    networks:
      - sab-network-dev

  gateway:
    image: tiger123/sab-gateway:master
    container_name: gateway
    ports:
      - "9000:9000"
    networks:
      - sab-network-dev
    depends_on:
      - registry
      - config-server
    environment:
      - EUREKA_SERVER=http://reg:8886/eureka

  sab-exeed-services:
    image: tiger123/sab-exceed-services:master
    container_name: sab-exceed-services
    ports:
      - "5005:8082"
    networks:
      - sab-network-dev
    depends_on:
      - registry
      - config-server
    environment:
      - EUREKA_SERVER=http://reg:8886/eureka
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  sab-network-dev:
    external: true
